env:
  - GO111MODULE=on
  # CODECOV_TOKEN set in Travis config.
go:
  - master
  - tip
language: go

script:
  - go test -race -covermode=atomic -coverprofile coverage.txt ./...

after_script:
  - go tool cover -html=coverage.txt -o coverage.html
  - bash <(curl -s https://codecov.io/bash)
