// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"flag"
)

// Injectors from wire.go:

func wireAuthConn(fs *flag.FlagSet, dsn dsnValue, user userValue, pass passValue) (*AuthConn, error) {
	conn, err := newBaseConn(dsn)
	if err != nil {
		return nil, err
	}
	authConn, err := newAuthConn(conn, fs, user, pass)
	if err != nil {
		return nil, err
	}
	return authConn, nil
}
