// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package cmd

import (
	"github.com/fgm/drupal_redis_stats/redis"
	"github.com/fgm/drupal_redis_stats/stats"
	"github.com/spf13/pflag"
)

// Injectors from wire.go:

func wireAuthConn(fs *pflag.FlagSet, dsn2 redis.DSNValue, user2 redis.UserValue, pass2 redis.PassValue) (*redis.AuthConn, error) {
	conn, err := redis.NewBaseConn(dsn2)
	if err != nil {
		return nil, err
	}
	authConn, err := redis.NewAuthConn(conn, fs, user2, pass2)
	if err != nil {
		return nil, err
	}
	return authConn, nil
}

func wireStatsScanner(fs *pflag.FlagSet, dsn2 redis.DSNValue, user2 redis.UserValue, pass2 redis.PassValue) (stats.Scanner, error) {
	conn, err := redis.NewBaseConn(dsn2)
	if err != nil {
		return nil, err
	}
	authConn, err := redis.NewAuthConn(conn, fs, user2, pass2)
	if err != nil {
		return nil, err
	}
	scanner := stats.NewScanner(authConn)
	return scanner, nil
}
