name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -race -covermode=atomic -coverprofile coverage.txt ./...

      - name: Build coverage
        run: go tool cover -html=coverage.txt -o coverage.html

      - name: Log coverage
        run: bash <(curl -s https://codecov.io/bash)
